bugs:
  batch_seqlen: 512
  hidden_dim: 512
  projection_dim: 2048
  n_heads: 8
  head_dim: 64
  n_layers: 12
  dropout_rate: 0.1
  dropatt_rate: 0.0

wiki:
  batch_seqlen: 1024
  hidden_dim: 512
  projection_dim: 2048
  n_heads: 8
  head_dim: 64
  n_layers: 12
  dropout_rate: 0.1
  dropatt_rate: 0.0

paraNMT:
  batch_seqlen: 384
  hidden_dim: 512
  projection_dim: 2048
  n_heads: 8
  head_dim: 64
  n_layers: 6
  dropout_rate: 0.1
  dropatt_rate: 0.0