n_epoch: 10
relative_pos: False
gathered: True
device: 'cuda'
batch_size: 24
gpu0_size: 8
update_step: 1
mixed_precision: True
decay_step: 20000
warmup_step: 0
clip_norm: 0.25
learning_rate: 0.001
weight_decay: 0.001
